LED_COUNT = 60
MAX_INTENSITY = 10

# FixedLightStrip
SCALE_FACTOR = 100

# ZenShiftLightStrip
ZEN_STEADY_PERIOD = 2
ZEN_SHIFT_PERIOD = 2

# PulseLightStrip
PULSE_STEADY_PERIOD = 5
PULSE_SHIFT_PERIOD = 7
PULSE_SHIFT_STEP = 2
